spring:
  application:
    name: gitlum
springdoc:
  api-docs:
    groups:
      enabled: true
    path: "/swagger-doc/v3/api-docs"
  swagger-ui:
    path: "/swagger-doc/swagger-ui.html"
gitlum:
  git:
    base-url: "https://api.github.com"
    repositories-uri: "/users/{user}/repos"
    branches-uri: "/repos/{user}/{repo}/branches"
  endpoints:
    base-url: "api/v1/git-repositories"
    get-repositories: "/get"
  request:
    default-page-number: "1"
    default-results-per-page: "3"
    user-param-key: "user"
    page-number-param-key: "page"
    results-per-page-param-value: "per_page"
    authorization-header-key: "Authorization"
    token-prefix: "Bearer: "