spring:
  application:
    name: gitlum
springdoc:
  api-docs:
    groups:
      enabled: true
    path: "/swagger-doc/v3/api-docs"
  swagger-ui:
    path: "/swagger-doc/swagger-ui.html"
constants:
  git-base-url: "https://api.github.com"
  user-repositories-uri: "/users/{user}/repos"
  repository-branches-uri: "/repos/{user}/{repo}/branches"
  git-repositories-base-url: "api/v1/git-repositories"
  get-git-repositories-uri: "/get"
  default-page-number: "1"
  default-results-per-page: "3"
  user-request-param-value: "user"
  page-request-param-value: "page"
  page-size-result-request-param-value: "per_page"
  authorization-header: "Authorization"
  token-prefix: "Bearer: "